name: murefi_env
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.21.2
  - scipy=1.7.3
  - watermark=2.3.0
  - pip:
    - aeppl==0.0.18
    - aesara==2.3.2
    - bletl==1.0.5
    - calibr8==6.4.0
    - fastprogress==1.0.0
    - matplotlib==3.5.1
    - murefi==5.1.0
    - pandas==1.4.1
    - pymc==4.0.0b2
